fos_user:
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: 'maven@dontdrinkandroot.net'
        sender_name: 'Maven Repository Manager'
    group:
        group_class:   App\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
        mailer: fos_user.mailer.noop
