image: philipsorst/php-testing:18-04-7-3

options:
    max-time: 10

pipelines:
    default:
        -   step:
                name: Test
                caches:
                    - composer
                #                    - node
                script:
                    - composer install --no-progress
                    #                    - yarn install
                    #                    - yarn encore dev
                    - APP_ENV=test bin/console doctrine:schema:create
                    - SYMFONY_DEPRECATIONS_HELPER="weak" bin/phpunit
        -   step:
                name: Deploy to production
                image: philipsorst/deployer
                deployment: production
                trigger: manual
                script:
                    - deployer deploy production
                    - deployer cleanup
