index:
    path: /
    controller: App\Controller\IndexController::index

repo_directory_index:
    path: /repos/{shortName}{path}
    controller: App\Controller\MavenRepositoryController::directoryIndex
    methods: [GET]
    requirements:
        shortName: '^[a-z0-9-_]+$'
        path: '/(.*/)?'

repo_download:
    path: /repos/{shortName}{path}
    controller: App\Controller\MavenRepositoryController::download
    methods: [GET]
    requirements:
        shortName: '^[a-z0-9-_]+$'
        path: '/.+'

repo_upload:
    path: /repos/{shortName}{path}
    controller: App\Controller\MavenRepositoryController::upload
    methods: [PUT, POST]
    requirements:
        shortName: '^[a-z0-9-_]+$'
        path: '/.+'