index:
    path: /
    controller: App\Controller\IndexController::index

app.health:
    path: /health
    controller: App\Controller\HealthAction

repo_directory_index:
    path: /repos/{shortName}{path}
    controller: App\Controller\MavenRepositoryController::directoryIndex
    methods: [ GET ]
    requirements:
        shortName: '^[a-z0-9-_]+$'
        path: '/(.*/)?'

repo_download:
    path: /repos/{shortName}{path}
    controller: App\Controller\MavenRepositoryController::download
    methods: [GET]
    requirements:
        shortName: '^[a-z0-9-_]+$'
        path: '/.+'

repo_upload:
    path: /repos/{shortName}{path}
    controller: App\Controller\MavenRepositoryController::upload
    methods: [PUT, POST]
    requirements:
        shortName: '^[a-z0-9-_]+$'
        path: '/.+'

group_directory_index:
    path: /groups/{shortName}{path}
    controller: App\Controller\MavenRepositoryGroupController::directoryIndex
    methods: [GET]
    requirements:
        shortName: '^[a-z0-9-_]+$'
        path: '/(.*/)?'

group_download:
    path: /groups/{shortName}{path}
    controller: App\Controller\MavenRepositoryGroupController::download
    methods: [GET]
    requirements:
        shortName: '^[a-z0-9-_]+$'
        path: '/.+'
