parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\MavenRepositoryController:
        arguments:
            $logger: '@monolog.logger.repository'
        tags: ['controller.service_arguments']

    App\Admin\MavenRepositoryAdmin:
        arguments: [~, App\Entity\MavenRepository, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Repositories, group: Repository Management }

    App\Service\MavenRepositoryService:
        arguments:
            $storageRoot: '%env(resolve:STORAGE_ROOT)%'