parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\RepositoryController:
        arguments: ['@monolog.logger.repository']
        tags: ['controller.service_arguments']

    App\Admin\RepositoryAdmin:
        arguments: [~, App\Entity\Repository, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Repositories, group: Repository Management }